### PR TITLE
Fix .off for one-time listeners

### LINKED ISSUE #4: .off does not remove listener functions added via .once
Due to how function comparison and listener removal is done, this library fails to remove listeners which have been added using `.once` if they are passed by function reference. Example:
```js
emitter.once('foo', myListener);
emitter.off('foo', myListener);
```

Since the emitter stores `.once` listeners in a mangled form (wrapped in a "once" function), it can not recognize that our function passed to "off" is the same function that is stored in the listeners array. As such, it fails to remove the listener.

### PR DESCRIPTION
**Pull request by rkaw92**
This basically fixes #4 and includes a unit test.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -63,6 +63,36 @@ function isFunction(arg) {
...
+ *
+ * @private
+ * @param {string} name - Name of event to listen to.
+ * @param {Function} fn - The function to represent this listener. Used for
+ *  comparison when removing the listener.
+ * @param {Function} run - The actual function to run when the named event is
+ *  emitted. This can differ if e.g. clean-up is needed. ".once" uses this.
+ * @param {Object} [ctx] - The context to use as "this" for the listener.
+ */
+function _addListener(name, fn, run, ctx) {
```
Comment (piecioshka) [inline src/index.js]: Please do not start private function with underscore.

File: src/index.js [hunk 2]
```diff
@@ -63,6 +63,36 @@ function isFunction(arg) {
     return typeof arg === 'function';
 }
 
+/**
+ * Add an event listener. Note that this method is not part of the EventEmitter
+ *  prototype to avoid polluting the namespace.
+ *
+ * @private
```
Comment (piecioshka) [inline src/index.js]: I don't like aliases, please you full form: `@access private`

File: src/index.js [hunk 3]
```diff
@@ -63,6 +63,36 @@ function isFunction(arg) {
...
+
+    // Push to private lists of listeners.
+    this._listeners.push({
+        name: name,
+        fn: fn,
+        run: run,
+        ctx: ctx
+    });
+
+    return this;
```
Comment (piecioshka) [inline src/index.js]: That return is never useful, especially in private functions.

File: src/index.js [hunk 4]
```diff
@@ -74,19 +104,9 @@ var EventEmitterProto = {
...
-
-        // Push to private lists of listeners.
-        this._listeners.push({
-            name: name,
-            fn: fn,
-            ctx: ctx
-        });
-
+        // For "on" functions, the runner is the same as the underlying
+        //  function. See "once" for when the distinction matters.
```
Comment (piecioshka) [inline src/index.js]: Redundant space after 2 first slashes.

**Review by piecioshka — CHANGES_REQUESTED** [review]
Try to fix reported issues

**Comment by piecioshka** [comment]
@rkaw92 ping 🏓

**Review by piecioshka — APPROVED** [review]
Thanks @rkaw92 !
